name: Download Artifact Example

on: [push]

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create artifact
      run: |
        echo "Hello World" > artifact.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact-name
        path: artifact.txt
  download-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: my-artifact-name
    - name: Create artifact directory
      run: |
         mkdir -p my-artifact-directory
         
    - name: Save artifact to repository code
      run: |
        mv my-artifact-name/* my-artifact-directory/
   
