name: Download Artifact Example

on: [push]

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: creating .txt file
      run: |
        mkdir -p path/to/artifact
        echo hello > path/to/artifact/world.txt

    - name: Download artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: my-artifact-name

    - name: Copy artifact to repository code
      run: |
        cp my-artifact-name/* .
