name: Download and Save Artifact Example

on: [push]

jobs:
  download-and-save-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: my-artifact-name

    - name: Create artifact directory
      run: |
        mkdir -p artifacts

    - name: Save artifact to repository code
      run: |
        mv my-artifact-name/* artifacts/
