name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create Directory
      run: mkdir Downloads
      
      
    - name: Adding files
      run: |
        cd Downloads
        echo 'A' > fileA.html
        echo 'B' > fileB.html
        echo 'C' > fileC.html
        cd ..
        
    - name: Uploading artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Sample-test
        path: Download
      
      
      
      
      
      
     
